name: IQMon
channels:
  - bokeh
  - conda-forge
  - defaults
dependencies:
  - astroplan=0.8
  - astropy=4.3.1
  - astroquery=0.4.3
  - bokeh=2.4.2
  - ccdproc=2.2.0
  - flask=1.0.3
  - ipython=7.27.0
  - numpy=1.21.2
  - photutils=1.1.0
  - pymongo=3.12.0
  - pyqt=5.12.3
  - pytest=6.2.5
  - python=3.7.10
  - pyyaml=5.4.1
  - requests=2.26.0
  - sep=1.2.0
  - pandas=1.3.5
  - ephem=4.1.2